### ISSUE TITLE
Getting error while running `g++ -DUSERSPACE -fpermissive -I/usr/include/bcc ebpf_wrapper.cc -lbcc -o ebpf_wrapper`

### ISSUE THREAD

**Issue by rajat85** [CN-TU/machine-learning-in-ebpf#3]
I'm using Ubuntu 22.2 and below is the output of `uname -a`:

**Linux rajat-ghosh 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux**

**Error:**

In file included from ebpf_wrapper.cc:21:
ebpf.c: In function ‘int filter(uint8_t*, shared_struct*)’:
ebpf.c:99:28: warning: ‘ethernet_t’ is deprecated: packet [-Wdeprecated-declarations]
   99 |         struct ethernet_t *ethernet;
      |                            ^~~~~~~~
In file included from ebpf.c:6,
                 from ebpf_wrapper.cc:21:
proto.h:24:8: note: declared here
   24 | struct ethernet_t {
      |        ^~~~~~~~~~
In file included from ebpf_wrapper.cc:21:
ebpf.c:100:28: warning: ‘ip_t’ is deprecated: packet [-Wdeprecated-declarations]
  100 |         struct ip_t       *ip;
      |                            ^~
In file included from ebpf.c:6,
                 from ebpf_wrapper.cc:21:
proto.h:49:8: note: declared here
   49 | struct ip_t {
      |        ^~~~
In file included from ebpf_wrapper.cc:21:
ebpf.c:101:28: warning: ‘udp_t’ is deprecated: packet [-Wdeprecated-declarations]
  101 |         struct udp_t      *l4;
      |                            ^~
In file included from ebpf.c:6,
                 from ebpf_wrapper.cc:21:
proto.h:97:8: note: declared here
   97 | struct udp_t {
      |        ^~~~~
In file included from ebpf_wrapper.cc:21:
ebpf.c:20:3: warning: invalid conversion from ‘void*’ to ‘ethernet_t*’ [-fpermissive]
   20 |   ({ void *_tmp = _cursor; _cursor += _len; _tmp; })
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   |
      |   void*
ebpf.c:106:28: note: in expansion of macro ‘cursor_advance’
  106 |                 ethernet = cursor_advance(cursor, sizeof(*ethernet));
      |                            ^~~~~~~~~~~~~~
ebpf.c:20:3: warning: invalid conversion from ‘void*’ to ‘ip_t*’ [-fpermissive]
   20 |   ({ void *_tmp = _cursor; _cursor += _len; _tmp; })
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   |
      |   void*
ebpf.c:121:22: note: in expansion of macro ‘cursor_advance’
  121 |                 ip = cursor_advance(cursor, sizeof(*ip));
      |                      ^~~~~~~~~~~~~~
ebpf.c:20:3: warning: invalid conversion from ‘void*’ to ‘udp_t*’ [-fpermissive]
   20 |   ({ void *_tmp = _cursor; _cursor += _len; _tmp; })
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   |
      |   void*
ebpf.c:149:22: note: in expansion of macro ‘cursor_advance’
  149 |                 l4 = cursor_advance(cursor, sizeof(*l4));
      |                      ^~~~~~~~~~~~~~
In file included from ebpf_wrapper.cc:21:
ebpf.c:179:80: warning: invalid conversion from ‘XFSMTableLeaf**’ to ‘void**’ [-fpermissive]
  179 |                 bool ret = hashmap__find(actual_struct->xfsm_table, &xfsm_idx, &xfsm_val);
      |                                                                                ^~~~~~~~~
      |                                                                                |
      |                                                                                XFSMTableLeaf**
In file included from ebpf_wrapper.cc:18:
hashmap.c:206:71: note:   initializing argument 3 of ‘bool hashmap__find(const hashmap*, const void*, void**)’
  206 | bool hashmap__find(const struct hashmap *map, const void *key, void **value)
      |                                                                ~~~~~~~^~~~~
In file included from ebpf_wrapper.cc:21:
ebpf.c:204:97: warning: invalid conversion from ‘XFSMTableLeaf**’ to ‘void**’ [-fpermissive]
  204 |                         bool ret = hashmap__find(actual_struct->xfsm_table, xfsm_key_allocated, &xfsm_val);
      |                                                                                                 ^~~~~~~~~
      |                                                                                                 |
      |                                                                                                 XFSMTableLeaf**
In file included from ebpf_wrapper.cc:18:
hashmap.c:206:71: note:   initializing argument 3 of ‘bool hashmap__find(const hashmap*, const void*, void**)’
  206 | bool hashmap__find(const struct hashmap *map, const void *key, void **value)
      |                                                                ~~~~~~~^~~~~
ebpf_wrapper.cc: In function ‘int main(int, char**)’:
ebpf_wrapper.cc:188:24: warning: invalid conversion from ‘void*’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
  188 |                 filter(buffer, &ss);
      |                        ^~~~~~
      |                        |
      |                        void*
In file included from ebpf_wrapper.cc:21:
ebpf.c:47:21: note:   initializing argument 1 of ‘int filter(uint8_t*, shared_struct*)’
   47 | int filter(uint8_t* skb, struct shared_struct* actual_struct) {
      |            ~~~~~~~~~^~~

**Comment by muxamilian** [comment]
In what you sent me, it looks like no error occurred. I only see warnings. Maybe it went through and you interpreted the warnings as errors? 

I see that you use a newer Ubuntu version, which contains a newer Python, C compiler etc. This might cause the code to not work. Unfortunately I don't have the resources to debug code which uses newer software versions.
